export const defaultSettings = {
  site_name: "ViVuGo",
  logo_url: "",
  contact_email: "",
  hotline: "",
  address: "",
  footer_text: "",
  footer_hotline: "",
  footer_email: "",
  footer_address: "",
  banners: [],
  password_min_length: 8,
  require_2fa: false,
  session_timeout_minutes: 120,
  allow_remember_login: true,
  notify_email_enabled: true,
  notify_sms_enabled: false,
  notify_push_enabled: true,
  admin_notification_email: "",
  default_language: "vi",
  timezone: "Asia/Ho_Chi_Minh",
  date_format: "dd/mm/yyyy",
  currency: "VND",
  payment_enabled: true,
  payment_gateway: "vnpay",
  vat_percent: 10,
  invoice_prefix: "VVG",
  auto_backup_enabled: false,
  backup_frequency: "daily",
  backup_time: "02:00",
  backup_retention_days: 7,
};

export const settingSections = [
  {
    id: "system",
    icon: "⚙️",
    title: "Thông Tin Hệ Thống",
    description: "Tên, logo, liên hệ và banner",
  },
  {
    id: "security",
    icon: "🔐",
    title: "Tài Khoản & Bảo Mật",
    description: "Mật khẩu, xác thực 2 lớp và phiên đăng nhập",
  },
  {
    id: "notification",
    icon: "🔔",
    title: "Thông Báo",
    description: "Email, SMS và thông báo trình duyệt",
  },
  {
    id: "locale",
    icon: "🌐",
    title: "Ngôn Ngữ & Vùng",
    description: "Ngôn ngữ, múi giờ và định dạng",
  },
  {
    id: "payment",
    icon: "💳",
    title: "Thanh Toán & Hóa Đơn",
    description: "Cổng thanh toán và thuế VAT",
  },
  {
    id: "backup",
    icon: "💾",
    title: "Sao Lưu Dữ Liệu",
    description: "Lịch tự động sao lưu và phục hồi",
  },
];
